### ISSUE TITLE
F-Droid fails to build

### ISSUE THREAD

**Issue by licaon-kter** [nova-video-player/aos-Fdroid#2]
Ref: https://f-droid.org/wiki/index.php?title=org.courville.nova/lastbuild_404912&oldid=285156

**Comment by courville** [comment]
@licaon-kter thanks for the heads up (again).
Seems that old `sdkmanager` are not aware of the `--install` option which is optional anyway: removing it.
I will tag a 4.49.16 and let's declare 4.49.12 dead on F-Droid.

**Comment by licaon-kter** [comment]
Mmmnope https://f-droid.org/wiki/index.php?title=org.courville.nova/lastbuild_404916&oldid=285455

**Comment by courville** [comment]
Yay ok let's try again.
FTR ndk location for android changes between r22 (`$ANDROID_SDK_ROOT/ndk-bundle`) and r21d (`$ANDROID_SDK_ROOT/android-sdk/ndk/21.3.6528147/`).
On F-Droid it seems that `ndk-bundle` directory is present and not the expected `ndk` one despite the `ndk: r21d` statement in `org.courville.nova.yml` file.
TODO: take into account the two cases in the build scripts.
Note to self:
```
wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
unzip commandlinetools-linux-6858069_latest.zip
mkdir -p android-sdk/cmdline-tools
mv cmdline-tools android-sdk/cmdline-tools/tools
export ANDROID_SDK_ROOT=$HOME/android-sdk
export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/cmdline-tools/tools/bin
sdkmanager ndk-bundle # -> android-sdk/ndk-bundle
sdkmanager "ndk;21.3.6528147" # (aka r21d) -> android-sdk/ndk/21.3.6528147/ no ndk-bundle
```

**Comment by courville** [comment]
Should be fixed now on v6.x branch and https://gitlab.com/software9/fdroiddata/-/commit/1571c8f39c1a3a2cc859b654ba0f42511bdc3113

**Comment by linsui** [comment]
https://monitor.f-droid.org/builds/log/org.courville.nova/600061#site-footer Could you please take a look? I see that there is some tricks to find the sdkmanager but it's not used everywhere.

**Comment by licaon-kter** [comment]
What should that install? Maybe we can do it in prebuild.

**Comment by courville** [comment]
OK my refactoring broke f-droid build. @linsui thanks for the heads up, I will look into it and I know what is wrong.

The issue is that f-droid official docker does not use latest `sdkmanager` and thanks to google wisdom `sdkmanager` depending on the version of `cmdline-tools` installed is located at a different path, relies on different version of `JAVA` and has slightly different syntax to install stuff.
Instead of using the overkill extended version of `android-setup.sh`, for my own CI, I used a lighter version `android-setup-light.sh` (all located in `AVP` repo) to speed my builds. I will re-switch to the non-light version to make f-droid happy.

@licaon-kter, all I need is `cmdline-tools;latest`, `ndk;23.1.7779620`, `cmake;3.18.1`, `platform-tools`, `build-tools;30.0.3`.

**Comment by courville** [comment]
@licaon-kter I should have all what I need in the prebuild.

Attempting build in https://gitlab.com/software9/fdroiddata/-/tree/novaFixV6Build waiting for the CI to provide a status.

**Comment by courville** [comment]
Yay it builds in the `registry.gitlab.com/fdroid/docker-executable-fdroidserver:master` docker (after some fiddling):
```
2022-04-17 17:38:04,647 INFO: Successfully built version 6.0.62 of org.courville.nova from e3f0bbfe555a2908bdac97a5b655b1ed0ba3ab14
2022-04-17 17:38:07,161 INFO: success: org.courville.nova
2022-04-17 17:38:07,161 INFO: Finished
2022-04-17 17:38:07,161 INFO: 1 build succeeded
```
But not on gitlab CI and I am in the dark:
```
Job's log exceeded limit of 4194304 bytes.
Job execution will continue but no more output will be collected.
```
P.S.: fiddling means contrary to f-droid CI docker and official build docker
* `apt-get install -y -t testing nasm` does not work
*  maven is not installed by default
* `gradlew-fdroid` is missing

EDIT: I have checked that `../AVP/android-setup-light.sh` does not generate any error any longer on CI by executing it in prebuild to witness its passing execution

**Comment by courville** [comment]
Here you go https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10929

**Comment by licaon-kter** [comment]
The Gitlab CI has some limitations, time to run, memory, storage space, log size, etc.

That MR builds fine for 099cb54a1a21bd583b69aeb2d0c32fe5ce48d23c 

What's next?

**Comment by courville** [comment]
@licaon-kter re-opening MR.

**Comment by licaon-kter** [comment]
and again https://monitor.f-droid.org/builds/log/org.courville.nova/602046#site-footer


fyi https://gitlab.com/fdroid/fdroiddata/-/commit/917965657568b904bea8a2b8fb3cd625977de1ed

**Comment by licaon-kter** [comment]
Looking at it I guess this path is invalid: https://github.com/nova-video-player/aos-boost-android-builder/blob/75732f2cf6a91da37aa4cb541aa09d21727586db/build.sh#L83

and we need to use https://github.com/boostorg/boost/releases/tag/boost-1.84.0 instead

right @courville ?

**Comment by courville** [comment]
@licaon-kter, thanks for the heads up (again). I reproduce on my side after a prebuilt binaires clean: I will fix it.

Since nova CI relies on pre-built binaries and somehow I managed to get boost built and pushed, I did not see the issue :-(

**Comment by courville** [comment]
@licaon-kter, sorry, I forgot to answer your question: the wget works on my side.

**Comment by courville** [comment]
@licaon-kter, I take it back you are right.

- jfrog archives no longer available
- github releases now available
- github releases format are boost-1.84.0 and not anymore boost-1_84_0 and tar xf directory as well

no wonder that it does not work...

**Comment by courville** [comment]
It builds on "my side" now. Will make a 6.2.48 release with proper tag to trigger f-droid build.

Thanks @licaon-kter for the hint.

**Comment by courville** [comment]
`git tag -a v6.2.48_c600248 -m 'v6.2.48 release'`

**Comment by licaon-kter** [comment]
Thanks https://gitlab.com/fdroid/fdroiddata/-/jobs/5893028378/artifacts/browse/tmp/

**Comment by courville** [comment]
@licaon-kter BTW in the past (I know) there was a handy page: https://f-droid.org/packages/org.courville.nova/lastbuild and for now https://monitor.f-droid.org/builds/log/org.courville.nova/ is not accessible. Would there be a magic url that would tell me what are the last status (failing/done build) apart from https://monitor.f-droid.org/builds where I need to dig up?
Thx

**Comment by licaon-kter** [comment]
Nope, just bookmark monitor running and keep pressing F5 :)
